Repository liquality/chainify, pull requests merged in 2021-12, with the labels that each got.

#480 fix: Check transaction status for solana and throw error if is not successful
  packages/solana-swap-provider/lib/SolanaSwapProvider.ts
Labels: ✅ Approved

#479 fix: check if status has SuccessValue
  packages/near-swap-provider/lib/NearSwapProvider.ts
Labels: ✅ Approved

#482 feat: Update terra htlc
  packages/terra-networks/lib/index.ts
  packages/terra-swap-provider/contract/src/contract.rs
  packages/terra-swap-provider/contract/src/error.rs
  packages/terra-swap-provider/lib/TerraSwapProvider.ts
  packages/terra-utils/lib/index.ts
  packages/types/lib/terra/index.ts
Labels: ✅ Approved

#481 Fix: Compare transaction lamports againts swapParams value
  packages/solana-swap-provider/lib/SolanaSwapProvider.ts
  packages/solana-utils/lib/index.ts
Labels: ✅ Approved

#478 fix: Handle terra tx status
  packages/terra-swap-provider/lib/TerraSwapProvider.ts
  packages/terra-wallet-provider/lib/TerraWalletProvider.ts
Labels: ✅ Approved

#484 fix: remove parseInt
  packages/ethereum-erc20-provider/lib/EthereumErc20Provider.ts
Labels: ✅ Approved

#486 fix: EthereumRpcProvider retrieve confirmations accurately
  packages/ethereum-rpc-provider/lib/EthereumRpcProvider.ts
Labels: ✅ Approved, size/XS

#487 feat: terra exportPrivateKey
  packages/terra-wallet-provider/lib/TerraWalletProvider.ts
  packages/terra-wallet-provider/test/unit/index.test.ts
Labels: ✅ Approved, size/M
