Repository liquality/chainify, pull requests merged in 2022-07, with the labels that each got.

#570 fix: evm work with >1000 amounts
  packages/evm/lib/utils.ts
  packages/evm/lib/wallet/EvmBaseWalletProvider.ts
  test/integration/clients/evm/config.ts
  test/integration/clients/evm/index.ts
  test/integration/deploy/evm.ts
  test/integration/environment/ganache.ts
Labels: 🔍 Ready for Review, size/S

#576 feat: improve multicall
  packages/evm/lib/chain/EvmChainProvider.ts
  packages/evm/lib/chain/EvmMulticallProvider.ts
  packages/evm/lib/types.ts
Labels: ✅ Approved, size/M

#577 fix: provide nft amount and nft stadard to the client
  packages/evm/lib/nft/MoralisNftProvider.ts
  packages/types/lib/Nft.ts
Labels: ✅ Approved, size/XS

#571 Fix: Update nft when swap changes & vise-versa
  packages/client/lib/Client.ts
Labels: ✅ Approved, size/XS

#578 fix/nfts-on-arbitrum
  packages/evm/lib/nft/CovalentNftProvider.ts
Labels: ✅ Approved, size/S
