Repository liquality/chainify, pull requests merged in 2022-04, with the labels that each got.

#529 fix: Account index
  packages/terra-networks/lib/index.ts
  packages/terra-wallet-provider/lib/TerraWalletProvider.ts
  packages/terra-wallet-provider/test/unit/index.test.ts
  test/integration/common.ts
Labels: 🔍 Ready for Review, size/M

#531 refactor: consistency across providers
  packages/bitcoin-ledger/lib/types.ts
  packages/bitcoin/lib/types.ts
  packages/bitcoin/lib/wallet/BitcoinBaseWallet.ts
  packages/bitcoin/lib/wallet/BitcoinHDWallet.ts
  packages/bitcoin/lib/wallet/BitcoinNodeWallet.ts
  packages/client/lib/Client.ts
  packages/client/lib/Swap.ts
  packages/evm-ledger/lib/EvmLedgerProvider.ts
  packages/evm-ledger/lib/types.ts
  packages/evm/lib/swap/EvmBaseSwapProvider.ts
  packages/evm/lib/swap/EvmSwapProvider.ts
  packages/evm/lib/utils.ts
  packages/evm/lib/wallet/EvmWalletProvider.ts
  packages/near/lib/swap/NearSwapProvider.ts
  packages/near/lib/types.ts
  packages/near/lib/wallet/NearWalletProvider.ts
  packages/terra/lib/swap/TerraSwapBaseProvider.ts
  packages/terra/lib/swap/TerraSwapProvider.ts
  packages/terra/lib/types/index.ts
  packages/terra/lib/wallet/TerraWalletProvider.ts
  packages/types/lib/Wallet.ts
  test/integration/chain/chain.test.ts
  test/integration/clients/bitcoin/clients.ts
  test/integration/clients/evm/clients.ts
  test/integration/clients/evm/config.ts
  test/integration/clients/near/clients.ts
  test/integration/clients/near/config.ts
  test/integration/clients/near/index.ts
  test/integration/clients/terra/clients.ts
  test/integration/clients/terra/config.ts
  test/integration/clients/terra/index.ts
  test/integration/index.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/XXL

#532 feat: fetch terra fees
  packages/client/lib/Chain.ts
  packages/client/lib/Fee.ts
  packages/terra/lib/chain/TerraChainProvider.ts
  test/integration/chain/chain.test.ts
  test/integration/clients/terra/index.ts
Labels: 🔍 Ready for Review, size/M

#534 Feat/solana integration v2
  package.json
  packages/solana/lib/SolanaSwapProvider.ts
  packages/solana/lib/SolanaWalletProvider.ts
  packages/solana/lib/chain/SolanaChainProvider.ts
  packages/solana/lib/index.ts
  packages/solana/lib/networks.ts
  packages/solana/lib/swap/SolanaSwapProvider.ts
  packages/solana/lib/types.ts
  packages/solana/lib/utils.ts
  packages/solana/lib/wallet/SolanaWalletProvider.ts
  packages/solana/package.json
  packages/solana/tsconfig.json
  test/integration/clients/index.ts
  test/integration/clients/solana/clients.ts
  test/integration/clients/solana/config.ts
  test/integration/clients/solana/index.ts
  test/integration/common.ts
  test/integration/config.ts
  test/integration/index.ts
  test/integration/types.ts
  test/integration/wallet/wallet.test.ts
  yarn.lock
Labels: ✅ Approved, size/XXL
