Repository liquality/chainify, pull requests merged in 2022-01, with the labels that each got.

#493 fix/near claim expiration check
  package.json
  packages/near-swap-provider/lib/NearSwapProvider.ts
  packages/near-swap-provider/lib/bytecode.ts
  test/integration/swap/singleChain.test.ts
Labels: ✅ Approved, size/L

#492 feat: added avax c-chain configuration
  packages/ethereum-networks/lib/index.ts
Labels: ✅ Approved, size/S

#491 fix: fuse_testnet chainId
  packages/ethereum-networks/lib/index.ts
Labels: ✅ Approved, size/XS

#497 fix: Return 0 when balance is undefined and fix tx confirmations
  packages/terra-rpc-provider/lib/TerraRpcProvider.ts
  packages/terra-utils/lib/index.ts
Labels: size/XS

#499 feat/swap provider
  packages/client/lib/Client.ts
  packages/client/lib/Swap.ts
  packages/client/lib/Wallet.ts
  packages/evm/lib/EvmBaseWalletProvider.ts
  packages/evm/lib/EvmChainProvider.ts
  packages/evm/lib/EvmSwapProvider.ts
  packages/evm/lib/EvmWalletProvider.ts
  packages/evm/lib/index.ts
  packages/evm/lib/typechain/LiqualityHTLC.ts
  packages/evm/lib/typechain/common.ts
  packages/evm/lib/typechain/index.ts
  packages/evm/package.json
  packages/types/lib/Transaction.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/XL

#498 feat: Change broadcast mechanism
  packages/terra-wallet-provider/lib/TerraWalletProvider.ts
Labels: ✅ Approved, size/S

#500 fix: Handle empty error state
  packages/terra-wallet-provider/lib/TerraWalletProvider.ts
Labels: ✅ Approved, size/XS
