Repository liquality/chainify, pull requests merged in 2022-06, with the labels that each got.

#546 Feat hw ledger factory
  .nvmrc
  package.json
  packages/bitcoin-ledger/lib/BitcoinLedgerProvider.ts
  packages/bitcoin-ledger/lib/types.ts
  packages/evm-ledger/lib/EvmLedgerProvider.ts
  packages/evm-ledger/lib/EvmLedgerSigner.ts
  packages/evm-ledger/lib/types.ts
  packages/evm-ledger/package.json
  packages/hw-ledger/lib/LedgerProvider.ts
  packages/hw-ledger/lib/WebHidTransportCreator.ts
  packages/hw-ledger/lib/index.ts
  packages/hw-ledger/lib/types.ts
  packages/hw-ledger/package.json
  test/integration/clients/bitcoin/clients.ts
  test/integration/clients/evm/clients.ts
  test/integration/environment/NodeTransportCreator.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/L

#547 fix: Getting solana token balance and estimating fee
  packages/solana/lib/chain/SolanaChainProvider.ts
Labels: ✅ Approved, size/S

#549 feat: changed tsonfig to target es6
  tsconfig.json
Labels: ✅ Approved, size/XS

#550 fix: address to lowercase to satisfy RSK
  packages/evm-ledger/lib/EvmLedgerProvider.ts
  packages/evm-ledger/lib/EvmLedgerSigner.ts
  packages/evm-ledger/lib/types.ts
  packages/evm-ledger/package.json
  yarn.lock
Labels: 🔍 Ready for Review, size/L

#548 feat: Integrate moralis as nft provider
  packages/evm/lib/index.ts
  packages/evm/lib/nft/CovalentNftProvider.ts
  packages/evm/lib/nft/EvmNftProvider.ts
  packages/evm/lib/nft/MoralisNftProvider.ts
  packages/evm/lib/nft/OpenSeaNftProvider.ts
  packages/evm/lib/types.ts
  packages/evm/package.json
  yarn.lock
Labels: ✅ Approved, size/L

#553 feat: fetch token details
  packages/client/lib/Chain.ts
  packages/evm/lib/chain/EvmChainProvider.ts
  packages/evm/package.json
  packages/terra/lib/chain/TerraChainProvider.ts
  packages/terra/lib/types/index.ts
  packages/terra/package.json
  packages/types/lib/Asset.ts
  yarn.lock
Labels: ✅ Approved, size/M

#556 feat: pass chain id during creation of provider
  packages/evm/lib/fee/EIP1559FeeProvider.ts
  packages/evm/lib/fee/RpcFeeProvider.ts
Labels: size/S

#555 fix: move NFTAsset type to global level
  packages/client/lib/Nft.ts
  packages/evm/lib/nft/CovalentNftProvider.ts
  packages/evm/lib/nft/EvmNftProvider.ts
  packages/evm/lib/nft/MoralisNftProvider.ts
  packages/evm/lib/nft/OpenSeaNftProvider.ts
  packages/evm/lib/types.ts
  packages/types/lib/Nft.ts
  packages/types/lib/index.ts
Labels: ✅ Approved, size/M

#554 feat: extend http client
  packages/client/lib/Http.ts
Labels: ✅ Approved, size/M

#562 fix: nft transfer accepts string instead of number to allow big numbers
  packages/client/lib/Nft.ts
  packages/evm/lib/nft/EvmNftProvider.ts
Labels: ✅ Approved, size/XS

#564 fix: replace toString with toFixed to prevent exponent error
  packages/evm/lib/utils.ts
Labels: 🔍 Ready for Review, size/XS

#557 fix: catch any errors during balance fetching
  packages/evm/lib/chain/EvmChainProvider.ts
  packages/evm/lib/chain/EvmMulticallProvider.ts
  packages/near/lib/chain/NearChainProvider.ts
  packages/solana/lib/chain/SolanaChainProvider.ts
  packages/terra/lib/chain/TerraChainProvider.ts
Labels: ✅ Approved, size/M

#563 feat: add gas limit margin of 50% for all evm transactions
  packages/evm/lib/wallet/EvmBaseWalletProvider.ts
Labels: ✅ Approved, size/M

#565 feat: add eip1559 fee api provider
  packages/evm/lib/fee/EIP1559FeeApiProvider.ts
  packages/evm/lib/index.ts
  test/integration/clients/evm/clients.ts
Labels: ✅ Approved, size/M

#566 feat: eip1559 provider
  packages/evm/lib/fee/EIP1559FeeApiProvider.ts
  packages/evm/lib/fee/EIP1559FeeApiProvider/ethereum.ts
  packages/evm/lib/fee/EIP1559FeeApiProvider/index.ts
  packages/evm/lib/fee/EIP1559FeeApiProvider/polygon.ts
  test/integration/clients/evm/clients.ts
Labels: 🔍 Ready for Review, size/L

#567 feat: add name service infrastructure and ENS
  packages/client/lib/Wallet.ts
  packages/evm/lib/index.ts
  packages/evm/lib/naming/EnsProvider.ts
  packages/evm/lib/wallet/EvmBaseWalletProvider.ts
  packages/evm/lib/wallet/EvmWalletProvider.ts
  packages/types/lib/Address.ts
  packages/types/lib/Naming.ts
  packages/types/lib/index.ts
Labels: 🔍 Ready for Review, size/M
