Repository liquality/chainify, pull requests merged in 2022-08, with the labels that each got.

#552 feat: Integrate jupiter
  packages/solana/lib/chain/SolanaChainProvider.ts
  packages/solana/lib/index.ts
  packages/solana/lib/nft/SolanaNftProvider.ts
  packages/solana/lib/types.ts
  packages/solana/lib/wallet/SolanaWalletProvider.ts
  packages/solana/package.json
  packages/types/lib/Asset.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/L

#580 fix: Solana fetching token by using official registry and some leftov…
  packages/solana/lib/chain/SolanaChainProvider.ts
  packages/solana/lib/nft/SolanaNftProvider.ts
  packages/solana/lib/wallet/SolanaWalletProvider.ts
  packages/solana/package.json
  packages/types/lib/Nft.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/M

#585 fix: add npm auth token in yarnrc.yml
  .changeset/old-chairs-refuse.md
  .yarnrc.yml
Labels: 🔍 Ready for Review, size/S

#587 Fix/yarnrc
  .changeset/old-chairs-refuse.md
  .github/workflows/release.yml
  .yarnrc.yml
  package.json
Labels: 🔍 Ready for Review, size/S

#594 feat: add fee estimation nfts
  .changeset/sharp-camels-help.md
  packages/client/lib/Nft.ts
  packages/evm/lib/nft/EvmNftProvider.ts
  packages/solana/lib/nft/SolanaNftProvider.ts
Labels: 🔍 Ready for Review, size/L

#597 feat: removing async from setters and getters is chains
  .changeset/fuzzy-cooks-dance.md
  packages/bitcoin/lib/wallet/BitcoinBaseWallet.ts
  packages/client/lib/Chain.ts
  test/integration/clients/evm/updateTransactionFee.behavior.ts
Labels: 🔍 Ready for Review, size/M

#599 Feat/asset native type
  .changeset/neat-avocados-join.md
  packages/evm/lib/chain/EvmChainProvider.ts
  packages/evm/lib/chain/EvmMulticallProvider.ts
  packages/evm/lib/index.ts
  packages/evm/lib/nft/CovalentNftProvider.ts
  packages/evm/lib/swap/EvmBaseSwapProvider.ts
  packages/evm/lib/utils.ts
  packages/evm/lib/wallet/EvmBaseWalletProvider.ts
  packages/evm/package.json
  packages/solana/lib/chain/SolanaChainProvider.ts
  packages/solana/lib/nft/SolanaNftProvider.ts
  packages/solana/lib/wallet/SolanaWalletProvider.ts
  packages/terra/lib/chain/TerraChainProvider.ts
  packages/terra/lib/wallet/TerraWalletProvider.ts
  packages/types/lib/Asset.ts
  test/integration/clients/bitcoin/config.ts
  test/integration/clients/evm/config.ts
  test/integration/clients/near/config.ts
  test/integration/clients/solana/config.ts
  test/integration/clients/terra/config.ts
  test/integration/clients/terra/index.ts
  test/integration/common.ts
  test/integration/wallet/wallet.test.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/L

#601 fix: export asL2Provider for optimism
  .changeset/orange-nails-grin.md
  packages/evm/lib/index.ts
Labels: 🔍 Ready for Review, size/S

#603 fix: patch @eth-optimism/sdk dependency
  .changeset/shy-suns-complain.md
  .yarn/patches/@eth-optimism-sdk-npm-1.1.5-3af49870d3
  package.json
  yarn.lock
Labels: 🔍 Ready for Review, size/M

#608 feat: setter and getter for optimism provider
  .changeset/popular-paws-sell.md
  packages/evm/lib/chain/OptimismChainProvider.ts
Labels: 🔍 Ready for Review, size/S

#610 fix: near fee as number
  .changeset/warm-days-jump.md
  packages/near/lib/chain/NearChainProvider.ts
Labels: 🔍 Ready for Review, size/S
