Repository liquality/chainify, pull requests merged in 2022-05, with the labels that each got.

#539 feat: optimism integration
  packages/evm/lib/networks.ts
  packages/types/lib/Asset.ts
Labels: 🔍 Ready for Review, size/S

#540 Feat/wallet chain update hooks
  packages/bitcoin/lib/swap/BitcoinSwapBaseProvider.ts
  packages/bitcoin/lib/swap/BitcoinSwapRpcProvider.ts
  packages/bitcoin/lib/wallet/BitcoinBaseWallet.ts
  packages/bitcoin/lib/wallet/BitcoinNodeWallet.ts
  packages/client/lib/Swap.ts
  packages/client/lib/Wallet.ts
  packages/evm-ledger/lib/EvmLedgerProvider.ts
  packages/evm/lib/swap/EvmBaseSwapProvider.ts
  packages/evm/lib/wallet/EvmWalletProvider.ts
  packages/near/lib/swap/NearSwapProvider.ts
  packages/near/lib/wallet/NearWalletProvider.ts
  packages/solana/lib/wallet/SolanaWalletProvider.ts
  packages/terra/lib/swap/TerraSwapProvider.ts
  packages/terra/lib/wallet/TerraWalletProvider.ts
Labels: 🔍 Ready for Review, size/M

#543 feat: add sign typed data
  packages/client/lib/Wallet.ts
  packages/evm/lib/types.ts
  packages/evm/lib/wallet/EvmWalletProvider.ts
  packages/evm/package.json
  test/integration/clients/evm/index.ts
  test/integration/clients/evm/signTypedData.behavior.ts
  test/integration/wallet/sign.typed.data.test.ts
  yarn.lock
Labels: ✅ Approved, size/L

#542 feat: add optimism chain provider
  packages/evm/lib/chain/OptimismChainProvider.ts
  packages/evm/lib/index.ts
  packages/evm/package.json
  packages/types/lib/Fees.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/XL

#544 feat: add github actions
  .github/workflows/test.yml
Labels: 🔍 Ready for Review, size/S
