Repository liquality/chainify, pull requests merged in 2022-03, with the labels that each got.

#518 feat: btc swap integration tests
  packages/bitcoin/lib/chain/esplora/BitcoinEsploraApiProvider.ts
  packages/bitcoin/lib/chain/jsonRpc/BitcoinJsonRpcProvider.ts
  packages/bitcoin/lib/index.ts
  packages/bitcoin/lib/swap/BitcoinSwapBaseProvider.ts
  packages/bitcoin/lib/swap/BitcoinSwapEsploraProvider.ts
  packages/bitcoin/lib/swap/BitcoinSwapRpcProvider.ts
  packages/bitcoin/lib/wallet/BitcoinHDWallet.ts
  packages/bitcoin/lib/wallet/BitcoinNodeWallet.ts
  packages/bitcoin/lib/wallet/IBitcoinWallet.ts
  packages/client/lib/Swap.ts
  packages/evm/lib/chain/EvmChainProvider.ts
  packages/near/lib/chain/NearChainProvider.ts
  packages/types/lib/Swap.ts
  test/integration/clients/bitcoin/clients.ts
  test/integration/clients/bitcoin/config.ts
  test/integration/clients/bitcoin/index.ts
  test/integration/common.ts
  test/integration/swap/swap.test.ts
Labels: 🔍 Ready for Review, size/L

#520 Terra packages
  .vscode/settings.json
  packages/near/lib/utils.ts
  packages/terra/lib/TerraChainProvider.ts
  packages/terra/lib/TerraSwapProvider.ts
  packages/terra/lib/TerraWalletProvider.ts
  packages/terra/lib/chain/TerraChainProvider.ts
  packages/terra/lib/constants.ts
  packages/terra/lib/index.ts
  packages/terra/lib/networks.ts
  packages/terra/lib/types.ts
  packages/terra/lib/utils.ts
  packages/terra/lib/wallet/TerraWalletProvider.ts
  packages/terra/package.json
  packages/types/lib/Asset.ts
  packages/types/lib/Transaction.ts
  packages/utils/lib/index.ts
  test/integration/chain/chain.test.ts
  test/integration/clients/bitcoin/config.ts
  test/integration/clients/evm/config.ts
  test/integration/clients/index.ts
  test/integration/clients/near/config.ts
  test/integration/clients/terra/clients.ts
  test/integration/clients/terra/config.ts
  test/integration/clients/terra/index.ts
  test/integration/common.ts
  test/integration/config.ts
  test/integration/index.ts
  test/integration/types.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/XL

#519 fix: Fee for terra tx
  packages/terra-swap-provider/lib/TerraSwapProvider.ts
Labels: ✅ Approved, size/S

#521 feat: add wallet & swap providers
  packages/terra/lib/index.ts
  packages/terra/lib/networks.ts
  packages/terra/lib/swap/TerraSwapProvider.ts
  packages/terra/lib/types.ts
  packages/terra/lib/utils.ts
  packages/terra/lib/wallet/TerraWalletProvider.ts
  packages/terra/package.json
  test/integration/clients/terra/clients.ts
  test/integration/clients/terra/config.ts
  test/integration/clients/terra/index.ts
  test/integration/common.ts
  test/integration/types.ts
  test/integration/wallet/wallet.test.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/L

#522 fix: Check if msgs exists in data before parsing them
  packages/terra-wallet-provider/lib/TerraWalletProvider.ts
Labels: ✅ Approved, size/XS

#523 feat: finalize terra packages
  .mocharc.yml
  packages/terra/lib/chain/TerraChainProvider.ts
  packages/terra/lib/constants.ts
  packages/terra/lib/index.ts
  packages/terra/lib/swap/TerraSwapBaseProvider.ts
  packages/terra/lib/swap/TerraSwapProvider.ts
  packages/terra/lib/types/fcd.ts
  packages/terra/lib/types/index.ts
  packages/terra/lib/utils.ts
  packages/terra/lib/wallet/TerraWalletProvider.ts
  packages/utils/lib/index.ts
  test/integration/clients/terra/clients.ts
  test/integration/clients/terra/index.ts
  test/integration/common.ts
Labels: 🔍 Ready for Review, size/L

#525 feat: btc ledger integration tests
  package.json
  packages/bitcoin-ledger/lib/BitcoinLedgerProvider.ts
  packages/bitcoin-ledger/lib/index.ts
  packages/bitcoin-ledger/package.json
  test/integration/clients/bitcoin/clients.ts
  test/integration/clients/bitcoin/config.ts
  test/integration/clients/bitcoin/index.ts
  test/integration/clients/evm/config.ts
  test/integration/clients/index.ts
  test/integration/common.ts
  test/integration/config.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/L

#528 V2 release
  .changeset/config.json
  package.json
  yarn.lock
Labels: 🔍 Ready for Review, size/M
