Repository liquality/chainify, pull requests merged in 2022-02, with the labels that each got.

#501 feat: nft implementation
  packages/client/lib/Http.ts
  packages/client/lib/Nft.ts
  packages/client/lib/index.ts
  packages/client/lib/types.ts
  packages/client/package.json
  packages/evm/lib/EvmNftProvider.ts
  packages/evm/lib/EvmSwapProvider.ts
  packages/evm/lib/typechain/ERC1155.ts
  packages/evm/lib/typechain/ERC1155__factory.ts
  packages/evm/lib/typechain/ERC721.ts
  packages/evm/lib/typechain/ERC721__factory.ts
  packages/evm/lib/typechain/LiqualityHTLC__factory.ts
  packages/evm/lib/typechain/index.ts
  packages/evm/lib/types.ts
  packages/evm/lib/utils.ts
  packages/types/lib/Transaction.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/XXL

#483 fix: improving terra usdt swaps
  packages/terra-swap-provider/lib/TerraSwapProvider.ts
  packages/terra-wallet-provider/lib/TerraWalletProvider.ts
Labels: ✅ Approved, size/M

#504 feat: complete swap happy route tests for EVM
  .mocharc.yml
  .vscode/settings.json
  packages/client/lib/Client.ts
  packages/client/lib/Swap.ts
  packages/evm-contracts/contracts/ILiqualityHTLC.sol
  packages/evm-contracts/contracts/LiqualityHTLC.sol
  packages/evm/lib/EvmSwapProvider.ts
  packages/evm/lib/chain/EvmChainProvider.ts
  packages/evm/lib/chain/EvmMulticallProvider.ts
  packages/evm/lib/index.ts
  packages/evm/lib/nft/EvmNftProvider.ts
  packages/evm/lib/swap/EvmBaseSwapProvider.ts
  packages/evm/lib/swap/EvmSwapProvider.ts
  packages/evm/lib/utils.ts
  packages/evm/lib/wallet/EvmBaseWalletProvider.ts
  packages/evm/lib/wallet/EvmWalletProvider.ts
  packages/evm/package.json
  packages/types/lib/index.ts
  packages/types/package.json
  packages/utils/lib/hex.ts
  packages/utils/lib/index.ts
  packages/utils/lib/math.ts
  packages/utils/lib/string.ts
  packages/utils/lib/swap.ts
  packages/utils/package.json
  test/integration/chain/chain.test.ts
  test/integration/clients/evm/config.ts
  test/integration/clients/evm/index.ts
  test/integration/clients/evm/updateTransactionFee.behavior.ts
  test/integration/clients/index.ts
  test/integration/common.ts
  test/integration/swap/swap.test.ts
  test/integration/types.ts
  test/integration/wallet/wallet.test.ts
  test/tsconfig.json
  turbo.json
  yarn.lock
Labels: 🔍 Ready for Review, size/XL

#506 feat: Add timeout mechanism if transaction is not processed for 30sec…
  packages/terra-wallet-provider/lib/TerraWalletProvider.ts
Labels: 🔍 Ready for Review, ✅ Approved, size/XS

#516 feat: Provide gasLimit outside in order to handle Astroport Swaps
  packages/terra-wallet-provider/lib/TerraWalletProvider.ts
Labels: ✅ Approved, size/S

#517 feat: btc wallet/chain integration tests
  .vscode/launch.json
  .vscode/tasks.json
  package.json
  packages/bitcoin/lib/chain/esplora/BitcoinEsploraApiProvider.ts
  packages/bitcoin/lib/chain/esplora/BitcoinEsploraBaseProvider.ts
  packages/bitcoin/lib/chain/esplora/BitcoinEsploraBatchBaseProvider.ts
  packages/bitcoin/lib/chain/jsonRpc/BitcoinJsonRpcBaseProvider.ts
  packages/bitcoin/lib/chain/jsonRpc/BitcoinJsonRpcProvider.ts
  packages/bitcoin/lib/chain/jsonRpc/types.ts
  packages/bitcoin/lib/fee/BitcoinFeeApiProvider.ts
  packages/bitcoin/lib/index.ts
  packages/bitcoin/lib/swap/BitcoinSwapBaseProvider.ts
  packages/bitcoin/lib/swap/BitcoinSwapEsploraProvider.ts
  packages/bitcoin/lib/wallet/BitcoinBaseWallet.ts
  packages/bitcoin/lib/wallet/BitcoinHDWallet.ts
  packages/bitcoin/lib/wallet/BitcoinNodeWallet.ts
  packages/bitcoin/package.json
  packages/client/lib/JsonRpc.ts
  packages/client/lib/index.ts
  packages/client/package.json
  packages/evm/package.json
  packages/utils/lib/crypto-hashing.d.ts
  packages/utils/lib/crypto.ts
  packages/utils/lib/index.ts
  packages/utils/lib/swap.ts
  packages/utils/package.json
  test/integration/chain/chain.test.ts
  test/integration/clients/bitcoin/behaviors/transactions.behavior.ts
  test/integration/clients/bitcoin/behaviors/wallet.behavior.ts
  test/integration/clients/bitcoin/clients.ts
  test/integration/clients/bitcoin/config.ts
  test/integration/clients/bitcoin/index.ts
  test/integration/clients/bitcoin/utils.ts
  test/integration/clients/evm/clients.ts
  test/integration/clients/evm/config.ts
  test/integration/clients/evm/index.ts
  test/integration/clients/index.ts
  test/integration/clients/near/config.ts
  test/integration/clients/near/index.ts
  test/integration/common.ts
  test/integration/config.ts
  test/integration/environment/btc/docker-compose.yaml
  test/integration/environment/btc/mine.sh
  test/integration/environment/btc/miner.Dockerfile
  test/integration/types.ts
  test/integration/wallet/wallet.test.ts
  yarn.lock
Labels: size/XXL
